lib/keila_web/router.ex
defmodule KeilaWeb.Router do
  require Keila
  use KeilaWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {KeilaWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug KeilaWeb.Meta.Plug
    plug KeilaWeb.AuthSession.Plug
    plug KeilaWeb.PutLocalePlug
    plug KeilaWeb.InstanceInfoPlug
  end

  # Non-authenticated Routes
  scope "/", KeilaWeb do
    pipe_through :browser

    get "/verify-sender/:token", SenderController, :verify_from_token
    get "/verify-sender/c/:token", SenderController, :cancel_verification_from_token
  end

  scope "/" do
    pipe_through :browser

    get "/api", KeilaWeb.ApiDocsController, :show
  end

  # Unauthenticated Routes
  scope "/", KeilaWeb do
    pipe_through [:browser, KeilaWeb.AuthSession.RequireNoAuthPlug]

    get "/auth/login", AuthController, :login
    post "/auth/login", AuthController, :post_login
    get "/auth/register", AuthController, :register
    post "/auth/register", AuthController, :post_register
    get "/auth/activate/:token", AuthController, :activate
    get "/auth/reset", AuthController, :reset
    post "/auth/reset", AuthController, :post_reset
    get "/auth/reset/:token", AuthController, :reset_change_password
    post "/auth/reset/:token", AuthController, :post_reset_change_password
  end

  # Authenticated Routes without activation requirement
  pipeline :activation_not_required do
    plug KeilaWeb.AuthSession.RequireAuthPlug, allow_not_activated: true
  end

  scope "/", KeilaWeb do
    pipe_through [:browser, :activation_not_required]

    get "/auth/activate", AuthController, :activate_required
    post "/auth/activate", AuthController, :post_activate_resend
  end

  # Authenticated Routes without a Project context
  scope "/", KeilaWeb do
    pipe_through [:browser, KeilaWeb.AuthSession.RequireAuthPlug]

    get "/auth/logout", AuthController, :logout

    get "/account", AccountController, :edit
    put "/account", AccountController, :post_edit

    Keila.if_cloud do
      get "/account/onboarding", CloudAccountController, :onboarding
      get "/account/await-subscription", CloudAccountController, :await_subscription
      delete "/account/subscription", CloudAccountController, :delete_subscription
    end

    get "/", ProjectController, :index
    get "/projects/new", ProjectController, :new
    post "/projects/new", ProjectController, :post_new

    get "/admin/users", UserAdminController, :index
    get "/admin/users/new", UserAdminController, :new
    post "/admin/users", UserAdminController, :create
    delete "/admin/users", UserAdminController, :delete
    get "/admin/users/:id/impersonate", UserAdminController, :impersonate
    get "/admin/users/:id/credits", UserAdminController, :show_credits
    post "/admin/users/:id/credits", UserAdminController, :create_credits

    Keila.if_cloud do
      get "/admin/users/:id/status", CloudAdminController, :show_user_account_status
      post "/admin/users/:id/status", CloudAdminController, :update_user_account_status
    end

    resources "/admin/shared-senders", SharedSenderAdminController
    get "/admin/shared-senders/:id/delete", SharedSenderAdminController, :delete_confirmation

    get "/admin/instance", InstanceAdminController, :show
  end

  # Authenticated Routes within a Project context
  scope "/", KeilaWeb do
    pipe_through [:browser, KeilaWeb.AuthSession.RequireAuthPlug, KeilaWeb.ProjectPlug]

    get "/projects/:project_id", ProjectController, :show
    get "/projects/:project_id/edit", ProjectController, :edit
    put "/projects/:project_id/edit", ProjectController, :post_edit
    get "/projects/:project_id/delete", ProjectController, :delete
    put "/projects/:project_id/delete", ProjectController, :post_delete

    resources "/projects/:project_id/senders", SenderController,
      only: [:index, :new, :edit, :delete]

    get "/projects/:project_id/senders/:id/delete", SenderController, :delete_confirmation

    get "/projects/:project_id/contacts", ContactController, :index
    get "/projects/:project_id/contacts/unsubscribed", ContactController, :index_unsubscribed
    get "/projects/:project_id/contacts/unreachable", ContactController, :index_unreachable
    get "/projects/:project_id/contacts/new", ContactController, :new
    post "/projects/:project_id/contacts/new", ContactController, :post_new
    get "/projects/:project_id/contacts/import", ContactController, :import
    get "/projects/:project_id/contacts/export", ContactController, :export
    get "/projects/:project_id/contacts/:id", ContactController, :edit
    put "/projects/:project_id/contacts/:id", ContactController, :post_edit
    delete "/projects/:project_id/contacts", ContactController, :delete

    get "/projects/:project_id/forms", FormController, :index
    get "/projects/:project_id/forms/new", FormController, :new
    get "/projects/:project_id/forms/:id", FormController, :edit
    put "/projects/:project_id/forms/:id", FormController, :post_edit
    delete "/projects/:project_id/forms", FormController, :delete

    get "/projects/:project_id/templates", TemplateController, :index
    get "/projects/:project_id/templates/new", TemplateController, :new
    post "/projects/:project_id/templates/new", TemplateController, :post_new
    get "/projects/:project_id/templates/:id", TemplateController, :edit
    put "/projects/:project_id/templates/:id", TemplateController, :post_edit
    get "/projects/:project_id/templates/:id/clone", TemplateController, :clone
    post "/projects/:project_id/templates/:id/clone", TemplateController, :post_clone
    delete "/projects/:project_id/templates", TemplateController, :delete

    get "/projects/:project_id/segments", SegmentController, :index
    get "/projects/:project_id/segments/new", SegmentController, :new
    post "/projects/:project_id/segments", SegmentController, :create
    get "/projects/:project_id/segments/:id", SegmentController, :edit
    get "/projects/:project_id/segments/:id/contacts_export", SegmentController, :contacts_export
    delete "/projects/:project_id/segments", SegmentController, :delete

    get "/projects/:project_id/campaigns", CampaignController, :index
    get "/projects/:project_id/campaigns/new", CampaignController, :new
    post "/projects/:project_id/campaigns/new", CampaignController, :post_new
    get "/projects/:project_id/campaigns/:id", CampaignController, :edit
    get "/projects/:project_id/campaigns/:id/stats", CampaignController, :stats
    get "/projects/:project_id/campaigns/:id/view", CampaignController, :view
    get "/projects/:project_id/campaigns/:id/share", CampaignController, :share
    post "/projects/:project_id/campaigns/:id/share", CampaignController, :post_share
    get "/projects/:project_id/campaigns/:id/clone", CampaignController, :clone
    post "/projects/:project_id/campaigns/:id/clone", CampaignController, :post_clone
    delete "/projects/:project_id/campaigns", CampaignController, :delete

    resources "/projects/:project_id/api_keys", ApiKeyController,
      only: [:index, :create, :new, :delete]
  end

  # Public Routes
  pipeline :browser_embeddable do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {KeilaWeb.PublicFormLayoutView, :root}
    plug :put_layout, false
    plug :put_secure_browser_headers, %{"content-security-policy" => "frame-ancestors *"}
    plug KeilaWeb.Meta.Plug
    plug KeilaWeb.PutLocalePlug
  end

  scope "/", KeilaWeb do
    pipe_through [:browser_embeddable]

    get "/forms/:id", PublicFormController, :show
    post "/forms/:id", PublicFormController, :submit
    get "/unsubscribe/:project_id/:recipient_id/:hmac", PublicFormController, :unsubscribe
    post "/unsubscribe/:project_id/:recipient_id/:hmac", PublicFormController, :unsubscribe
    get "/double-opt-in/:form_id/:form_params_id/:hmac", PublicFormController, :double_opt_in
    post "/double-opt-in/:form_id/:form_params_id/:hmac", PublicFormController, :double_opt_in

    get "/double-opt-in/:form_id/:form_params_id/:hmac/cancel",
        PublicFormController,
        :cancel_double_opt_in

    post "/double-opt-in/:form_id/:form_params_id/:hmac/cancel",
         PublicFormController,
         :cancel_double_opt_in

    get "/r/:encoded_url/:recipient_id/:hmac", TrackingController, :track_open
    get "/c/:encoded_url/:recipient_id/:link_id/:hmac", TrackingController, :track_click

    get "/archive/:id", PublicCampaignController, :show

    # DEPRECATED: These routes will be removed in a future Keila release
    get "/unsubscribe/:project_id/:contact_id", PublicFormController, :unsubscribe
    post "/unsubscribe/:project_id/:contact_id", PublicFormController, :unsubscribe
  end

  scope "/uploads", KeilaWeb do
    pipe_through :browser

    get "/:filename", LocalFileController, :serve
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :open_api do
    plug OpenApiSpex.Plug.PutApiSpec, module: KeilaWeb.ApiSpec
  end

  scope "/api/v1" do
    pipe_through [:api, :open_api]
    get "/openapi", OpenApiSpex.Plug.RenderSpec, []
  end

  scope "/api/v1", KeilaWeb do
    pipe_through [:api, :open_api]

    resources "/contacts", ApiContactController, only: [:index, :show, :create, :update, :delete]
    patch "/contacts/:id/data", ApiContactController, :update_data
    post "/contacts/:id/data", ApiContactController, :replace_data

    resources "/campaigns", ApiCampaignController,
      only: [:index, :show, :create, :update, :delete]

    post "/campaigns/:id/actions/send", ApiCampaignController, :deliver
    post "/campaigns/:id/actions/schedule", ApiCampaignController, :schedule

    resources "/forms", ApiFormController, only: [:index, :show, :create, :update, :delete]
    post "/forms/:id/actions/submit", ApiFormController, :submit

lib/keila_web/views/layout_view.ex
defmodule KeilaWeb.LayoutView do
  use KeilaWeb, :view
  use PhoenixHTMLHelpers
  require Keila
  import KeilaWeb.IconHelper

  def menu_link(conn, controller, action, route_params, label, opts \\ []) do
    path = get_path(conn, controller, action, route_params)
    menu_link(conn, path, label, opts)
  end

  defp menu_link(conn, path, label, opts) when is_binary(path) do
    class =
      [
        "menu-link",
        if(active_path?(conn, path, opts), do: "menu-link--active"),
        if(conn.request_path == path, do: "menu-link--active-exact"),
        if(Keyword.get(opts, :indent) == 1, do: "ml-4")
      ]
      |> Enum.filter(& &1)
      |> Enum.join(" ")

    icon = Keyword.get(opts, :icon, nil)

    assigns = %{label: label, icon: icon, path: path, class: class}

    ~H"""
    <a href={@path} class={@class}>
      <%= if @icon do %>
        <span class="flex h-4 w-4">
          {render_icon(@icon)}
        </span>
      <% end %>
      {@label}
    </a>
    """
  end

  defp get_path(conn, controller, action, route_params) do
    params = [conn | [action | route_params]]
    apply(Routes, :"#{controller}_path", params)
  end

  @spec active_path?(Plug.Conn.t(), String.t(), Keyword.path()) :: boolean()
  def active_path?(conn = %{request_path: current_path}, path, ops) do
    exact? = Keyword.get(ops, :exact, false)

    if exact? do
      path == current_path
    else
      exclude =
        Keyword.get(ops, :exclude, [])
        |> Enum.map(fn {controller, action, route_params} ->
          get_path(conn, controller, action, route_params)
        end)

      String.starts_with?(current_path, path) && current_path not in exclude
    end
  end

  defp show_project_submenu?(conn, current_project) do
    conn.request_path in [
      Routes.project_path(conn, :show, current_project.id),
      Routes.project_path(conn, :edit, current_project.id)
    ] ||
      String.starts_with?(conn.request_path, Routes.sender_path(conn, :index, current_project.id))
  end
end

lib/keila_web/templates/layout/_footer.html.heex
<footer class="col-span-full bg-gray-950 mt-4 py-8 text-sm text-gray-100 border-t-2 border-gray-800">
  <div class="max-w-7xl mx-auto px-2 py-4 sm:px-6 lg:px-8">
    <div class="container grid sm:grid-cols-3">
      <div>
        <h3 class="flex gap-2 mb-4">
          <span class="flex h-12 w-12 text-emerald-600">
            {render_icon(:logo)}
          </span>
          <p>
            <span class="font-bold">Keila</span> <br /> {gettext("Open Source Newsletters")}
          </p>
        </h3>
      </div>
      <div>
        <h3 class="font-bold mb-4">{gettext("Docs")}</h3>
        <ul>
          <li>
            <a class="block hover:underline" href="https://www.keila.io/docs/senders">
              {gettext("Usage")}
            </a>
          </li>
          <li>
            <a class="block hover:underline" href="https://www.keila.io/docs/installation">
              {gettext("Self-hosting")}
            </a>
          </li>
        </ul>
      </div>
      <div>
        <h3 class="font-bold mb-4">{gettext("Community")}</h3>
        <ul>
          <li>
            <a class="block hover:underline" href="https://www.github.com/pentacent/keila">
              GitHub
            </a>
          </li>
          <li>
            <a class="block hover:underline" href="https://www.twitter.com/keila_io">Twitter</a>
          </li>
          <li>
            <a class="block hover:underline" href="https://app.keila.io/forms/frm_GX8qGEZd">
              {gettext("Newsletter")}
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

lib/keila_web/templates/layout/_menu.html.heex
<%= if @current_user do %>
  <aside class="flex bg-gray-800 overflow-y-auto">
    <div id="main-menu" class="container sm:h-screen sm:flex sm:flex-col">
      <input id="main-menu-toggle" type="checkbox" aria-hidden="true" class="hidden" />
      <div class="absolute inset-y-0 h-14 top-2 right-4 flex items-center sm:hidden">
        <label
          id="show-main-menu"
          for="main-menu-toggle"
          class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
          aria-expanded="false"
        >
          <span class="sr-only">{gettext("Open menu")}</span>
          <span class="inline-flex h-6 w-6">{render_icon(:menu)}</span>
        </label>
        <label
          id="hide-main-menu"
          for="main-menu-toggle"
          class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white"
          aria-expanded="false"
        >
          <span class="sr-only">{gettext("Close menu")}</span>
          <span class="inline-flex h-6 w-6">{render_icon(:x)}</span>
        </label>
      </div>
      <div class="shrink-0 grow-0 flex mx-4 text-white">
        <a href={Routes.project_path(@conn, :index)} class="flex items-center sm:h-24 my-4">
          <span class="flex justify-end h-10 w-10">
            {render_icon(:logo)}
          </span>
          <span class="text-2xl font-light">Keila</span>
        </a>
      </div>
      <nav class="font-medium hidden flex-col gap-1 mt-2 mb-4 sm:flex flex-grow">
        <%= if is_nil(assigns[:current_project]) do %>
          {menu_link(@conn, :project, :index, [], gettext("Projects"),
            exact: true,
            icon: :collection
          )}
        <% else %>
          <a
            href={Routes.project_path(@conn, :index)}
            class="block text-xs font-light text-white my-2 align-middle hover:underline"
          >
            {gettext("Back to projects overview")}
          </a>
          {menu_link(@conn, :project, :show, [@current_project.id], @current_project.name,
            exact: true,
            icon: :desktop_computer
          )}
          <%= if show_project_submenu?(@conn, @current_project) do %>
            {menu_link(
              @conn,
              :project,
              :edit,
              [@current_project.id],
              gettext("Project settings"),
              exact: true,
              icon: :cog,
              indent: 1
            )}
            {menu_link(@conn, :sender, :index, [@current_project.id], gettext("Senders"),
              exact: false,
              icon: :speakerphone,
              indent: 1
            )}
          <% end %>
          {menu_link(@conn, :contact, :index, [@current_project.id], gettext("Contacts"),
            icon: :user_group,
            exclude: [
              {:contact, :new, [@current_project.id]},
              {:contact, :import, [@current_project.id]}
            ]
          )}
          <%= if String.starts_with?(@conn.request_path, Routes.contact_path(@conn, :index, @current_project.id)) do %>
            {menu_link(@conn, :contact, :new, [@current_project.id], gettext("Create contact"),
              exact: true,
              icon: :document_add,
              indent: 1
            )}
            {menu_link(
              @conn,
              :contact,
              :import,
              [@current_project.id],
              gettext("Import contacts"),
              exact: true,
              icon: :user_add,
              indent: 1
            )}
          <% end %>
          {menu_link(@conn, :segment, :index, [@current_project.id], gettext("Segments"),
            icon: :filter,
            exclude: [{:form, :new, [@current_project.id]}]
          )}
          {menu_link(@conn, :form, :index, [@current_project.id], gettext("Forms"),
            icon: :template,
            exclude: [{:form, :new, [@current_project.id]}]
          )}
          <%= if String.starts_with?(@conn.request_path, Routes.form_path(@conn, :index, @current_project.id)) do %>
            {menu_link(@conn, :form, :new, [@current_project.id], gettext("Create form"),
              exact: true,
              icon: :document_add,
              indent: 1
            )}
          <% end %>
          {menu_link(@conn, :template, :index, [@current_project.id], gettext("Templates"),
            icon: :color_swatch,
            exclude: [{:template, :new, [@current_project.id]}]
          )}
          <%= if String.starts_with?(@conn.request_path, Routes.template_path(@conn, :index, @current_project.id)) do %>
            {menu_link(
              @conn,
              :template,
              :new,
              [@current_project.id],
              gettext("Create template"),
              exact: true,
              icon: :document_add,
              indent: 1
            )}
          <% end %>
          {menu_link(@conn, :campaign, :index, [@current_project.id], gettext("Campaigns"),
            icon: :at_symbol,
            exclude: [{:campaign, :new, [@current_project.id]}]
          )}
          <%= if String.starts_with?(@conn.request_path, Routes.campaign_path(@conn, :index, @current_project.id)) do %>
            {menu_link(
              @conn,
              :campaign,
              :new,
              [@current_project.id],
              gettext("Create campaign"),
              exact: true,
              icon: :document_add,
              indent: 1
            )}
          <% end %>
          {menu_link(@conn, :api_key, :index, [@current_project.id], gettext("API Keys"),
            exact: true,
            icon: :code
          )}
        <% end %>
        <div class="hidden sm:block sm:flex-grow"></div>
        {menu_link(@conn, Routes.account_path(@conn, :edit), gettext("Account"), icon: :user)}
        <%= if assigns[:is_admin?] do %>
          {menu_link(@conn, Routes.user_admin_path(@conn, :index), gettext("Users"), icon: :users)}
          {menu_link(@conn, Routes.shared_sender_admin_path(@conn, :index), gettext("Senders"),
            icon: :speakerphone
          )}
          {menu_link(
            @conn,
            Routes.instance_admin_path(@conn, :show),
            dgettext("admin", "System Info"),
            icon: :information_circle
          )}
        <% end %>
        {menu_link(@conn, Routes.auth_path(@conn, :logout), gettext("Sign out"), icon: :logout)}
      </nav>
    </div>
  </aside>
<% else %>
  <header class="bg-gray-900">
    <div class="container my-4 text-emerald-500 flex justify-center">
      <a href={Routes.project_path(@conn, :index)} class="inline-flex items-start">
        <span class="flex h-11 w-11 -mr-1">
          {render_icon(:logo)}
        </span>
        <span class="text-3xl font-light">Keila</span>
      </a>
    </div>
  </header>
<% end %>

lib/keila_web/templates/layout/app.html.heex
<main role="main" class="static-container flex-grow bg-gray-950 text-gray-300 min-h-screen">
  <%= if Phoenix.Flash.get(@flash, :info) do %>
    <div class="bg-emerald-200 text-black" role="alert">
      <p class="container py-5 my-0">{Phoenix.Flash.get(@flash, :info)}</p>
    </div>
  <% end %>
  <%= if Phoenix.Flash.get(@flash, :errors) do %>
    <div class="bg-yellow-200" role="alert">
      <p class="container py-5 my-0">{Phoenix.Flash.get(@flash, :error)}</p>
    </div>
  <% end %>
  <%= if assigns[:is_admin?] && assigns[:instance_updates_available?] do %>
    <div class="bg-amber-200 text-black" role="alert">
      <p class="container py-5 my-0">
        <a href={~p"/admin/instance"}>
          {dgettext("admin", "A new version of Keila is available.")}
          <span class="underline">{dgettext("admin", "Read more")}</span>
        </a>
      </p>
    </div>
  <% end %>
  <%= Keila.if_cloud do %>
    <%= if assigns[:current_account] do %>
      <%= case @current_account.status do %>
        <% :default -> %>
          <div class="bg-gradient-to-b from-emerald-200 to-emerald-300 text-black" role="alert">
            <p class="container py-5 my-0">
              <a href={~p"/account"}>
                {dgettext(
                  "cloud",
                  "Welcome to Keila, have a look around! To start sending emails, please choose a subscription."
                )}
                <span class="underline">{dgettext("cloud", "Select plan")}</span>
              </a>
            </p>
          </div>
        <% :onboarding_required -> %>
          <div class="bg-gradient-to-b from-emerald-200 to-emerald-300 text-black" role="alert">
            <p class="container py-5 my-0">
              <a href={~p"/account/onboarding"}>
                {dgettext(
                  "cloud",
                  "Before you can start sending emails, we need some more information about your account."
                )}
                <span class="underline">{dgettext("cloud", "Complete information")}</span>
              </a>
            </p>
          </div>
        <% :under_review -> %>
          <div class="bg-gradient-to-b from-emerald-200 to-emerald-300 text-black" role="alert">
            <p class="container py-5 my-0">
              <a href={~p"/account/onboarding"}>
                {dgettext(
                  "cloud",
                  "Your account is currently under review. Sending emails will be enabled once the review has been completed."
                )}
                <span class="underline">
                  {dgettext("cloud", "Update account information")}
                </span>
              </a>
            </p>
          </div>
        <% _other -> %>
          <% system_disruption_message = KeilaCloud.system_disruption_message() %>
          <%= if system_disruption_message do %>
            <div class="bg-amber-200 text-black" role="alert">
              <p class="container py-5 my-0">
                <a href="https://status.keila.io">
                  {system_disruption_message}
                  <span class="underline">
                    {dgettext("cloud", "Status page")}
                  </span>
                </a>
              </p>
            </div>
          <% end %>
      <% end %>
    <% end %>
  <% end %>
  {@inner_content}
</main>

lib/keila_web/templates/layout/live.html.leex
<p class="alert alert-info" role="alert"
  phx-click="lv:clear-flash"
  phx-value-key="info"><%= live_flash(@flash, :info) %></p>

<p class="alert alert-danger" role="alert"
  phx-click="lv:clear-flash"
  phx-value-key="error"><%= live_flash(@flash, :error) %></p>

<%= @inner_content %>

lib/keila_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {csrf_meta_tag()}
    <title>
      {get_meta(
        @conn,
        view_module(@conn),
        view_template(@conn),
        :title,
        gettext("Open Source Newsletter Tool")
      ) <> " · Keila"}
    </title>
    <meta property="og:image" content={Routes.static_url(@conn, "/images/og_image.png")} />
    <meta property="og:description" content="Open Source Newsletters" />
    <meta name="twitter:card" content="summary" />
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/css/app.css")} />
    <script
      defer
      phx-track-static
      type="text/javascript"
      src={Routes.static_path(@conn, "/js/app.js")}
    >
    </script>
  </head>
  <%= if @current_user do %>
    <body class="grid grid-cols-1 sm:grid-cols-[16em,1fr]">
      {render("_menu.html", assigns)}
      <div>
        {@inner_content}
        {render("_footer.html", assigns)}
      </div>
    </body>
  <% else %>
    <body class="grid grid-cols-1">
      {render("_menu.html", assigns)}
      {@inner_content}
      {render("_footer.html", assigns)}
    </body>
  <% end %>
</html>